source "https://rubygems.org"

ruby "2.7.0"

gem "activerecord", ">= 6.0.3.1", :require => "active_record"
gem "chronic"
gem "erubis"
gem "json", ">= 2.3.0"
gem "multi_json"
gem "octokit"
gem "oj"
gem "pg", "~> 0.18"
gem "rack-sassc", ">= 0.1.0"
gem "rack_csrf", ">= 2.6.0", :require => "rack/csrf"
gem "rake"
gem "sassc"
gem "sinatra", ">= 2.0.8.1"
gem "thin", ">= 1.7.2"
