source "https://rubygems.org"

# Padrino supports Ruby version 2.2.2 and later
ruby "2.7.0"

gem "activerecord", ">= 3.1", :require => "active_record"
gem "chronic"
gem "dalli"
gem "erubis"
gem "json", ">= 2.3.0"
gem "multi_json"
gem "octokit"
gem "oj"
gem "padrino", "0.14.4"
gem "pg", "~> 0.18"
gem "rack-sassc"
gem "rack_csrf", :require => "rack/csrf"
gem "rake"
gem "sanitize", ">= 5.2.1"
gem "sassc"
gem "sinatra"
gem "sinatra-flash", :require => "sinatra/flash"
gem "therubyracer"
gem "thin"
gem "yajl-ruby", :require => "yajl"
