source "https://rubygems.org"

# Padrino supports Ruby version 2.2.2 and later
ruby "2.7.0"

gem "activerecord", ">= 6.0.3.1", :require => "active_record"
gem "chronic"
gem "dalli"
gem "erubis"
gem "json", ">= 2.3.0"
gem "multi_json"
gem "octokit"
gem "oj"
gem "padrino", "0.14.4"
gem "pg", "~> 0.18"
gem "rack-sassc", ">= 0.1.0"
gem "rack_csrf", ">= 2.6.0", :require => "rack/csrf"
gem "rake"
gem "sanitize", ">= 5.2.1"
gem "sassc"
gem "sinatra", ">= 2.0.8.1"
gem "sinatra-flash", ">= 0.3.0", :require => "sinatra/flash"
gem "therubyracer"
gem "thin", ">= 1.7.2"
gem "yajl-ruby", :require => "yajl"
